plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - '.idea/workspace.xml'
  - 'node_modules/*'
include:
  - LICENSE.md

theme: jekyll-theme-cayman

show_downloads: false
markdown: kramdown
